# Generated by Django 4.2.3 on 2023-08-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ManyToManyField(related_name='is_in_shopping_cart', to='recipe.recipe'),
        ),
    ]
