# Generated by Django 4.2.3 on 2023-07-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredientsrecipe_remove_recipe_tag_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
    ]
