# Generated by Django 4.2.3 on 2023-08-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
